#!/bin/bash
# Description: sign bytestreams with servers key, publisc key is published on another port

#. /etc/init.d/functions

PID_SIGN=-1
PID_PUBLISH=-1

start() {
    PID_SIGN=$(python $SIGNER_PATH/service/main.py)
    PID_PUBLISH=$(python $SIGNER_PATH/service/publish.py)
}

stop() {
    kill $PID_SIGN
    kill $PID_PUBLISH
}

status() {
     $(SIGNER_PATH)/service/main.py
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0
